---
- name: Copy the redis exporter systemd service file
  template:
    src: redis_exporter.service.j2
    dest: /etc/systemd/system/redis_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart redis_exporter
